services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - ${RABBIT_PORT}:5672
      - ${RABBIT_ADMIN_PORT}:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
