services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_PLUGINS_DIR: /opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    ports:
      - ${RABBIT_PORT}:5672
      - ${RABBIT_ADMIN_PORT}:15672
    volumes:
      - ./plugins:/usr/lib/rabbitmq/plugins
      - ./rabbitmq_data:/var/lib/rabbitmq
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_management &&
        rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
        rabbitmq-server
      "
