global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets:
          - 'bot:9000'
    metrics_path: /metrics
    scheme: http

  - job_name: 'users'
    static_configs:
      - targets:
          - 'users:9001'
    metrics_path: /metrics
    scheme: http

  - job_name: 'notifications'
    static_configs:
      - targets:
          - 'notifications:9002'
    metrics_path: /metrics
    scheme: http

  - job_name: 'proxy'
    static_configs:
      - targets:
          - 'proxy:9003'
    metrics_path: /metrics
    scheme: http
