FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry
COPY ./apps/notifications/pyproject.toml ./apps/notifications/poetry.lock* /app/
RUN poetry config virtualenvs.create false && poetry lock --no-update && poetry install --no-interaction --no-ansi

COPY ./apps/notifications/notifications /app/notifications
COPY ./libs /app/libs

ARG NOTIFICATIONS_PORT
EXPOSE ${NOTIFICATIONS_PORT}

CMD [ "python", "notifications/main.py" ]
