FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry
COPY ./apps/bot/pyproject.toml ./apps/bot/poetry.lock* /app/
RUN poetry config virtualenvs.create false && poetry lock --no-update && poetry install --no-interaction --no-ansi

COPY ./apps/bot/bot /app/bot
COPY ./libs /app/libs

ARG BOT_PORT
EXPOSE ${BOT_PORT}

CMD [ "python", "bot/main.py" ]
