FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry
COPY ./apps/proxy/pyproject.toml ./apps/proxy/poetry.lock* /app/
RUN poetry config virtualenvs.create false && poetry lock --no-update && poetry install --no-interaction --no-ansi

COPY ./apps/proxy/proxy /app/proxy
COPY ./libs /app/libs

ARG PROXY_PORT
EXPOSE ${PROXY_PORT}

CMD [ "python", "proxy/main.py" ]
