FROM oven/bun:latest

WORKDIR /app

COPY ./apps/frontend/package.json ./apps/frontend/bun.lockb* ./

RUN bun install --frozen-lockfile

COPY ./apps/frontend /app

ARG FRONTEND_PORT
EXPOSE ${FRONTEND_PORT}

ENV FRONTEND_PORT=${FRONTEND_PORT}

CMD bash -c "bun run build && bun run preview -- --port ${FRONTEND_PORT}"
