"""add user model

Revision ID: af6e1676dabe
Revises:
Create Date: 2024-12-08 14:55:47.979101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af6e1676dabe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        schema="users",
    )
    op.create_index("user_created_at_index", "users", ["created_at"], unique=False, schema="users")
    op.create_index("user_username_index", "users", ["username"], unique=False, schema="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_username_index", table_name="users", schema="users")
    op.drop_index("user_created_at_index", table_name="users", schema="users")
    op.drop_table("users", schema="users")
    # ### end Alembic commands ###
